name: Build Android and iOS
on:
  push:
    branches:
      - development
jobs:
  install-depedency:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install

  build-android:
    needs: install-depedency
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm i @react-native-community/cli-platform-android
      - name: Build Android Release
        run: |
          cd android && chmod +x gradlew && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

  install-apk-to-emu:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.USERNAME_SERVER }}
        password: ${{ secrets.PASSWORD_SERVER }}
        port: 4345
        script: adb devices && adb install -r ~/apps-mobile/github/workspace/app-release.apk/app-release.apk

  automated-test-apk:
    needs: install-apk-to-emu
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.USERNAME_SERVER }}
        password: ${{ secrets.PASSWORD_SERVER }}
        port: 4345
        script: cd ~/appium-autotest && mvn clean test